# Generated by Django 2.2.7 on 2020-04-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('breath', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('chills', models.BooleanField(default=False)),
                ('sudden_confusion', models.BooleanField(default=False)),
                ('digestive', models.BooleanField(default=False)),
                ('pink_eye', models.BooleanField(default=False)),
                ('loss_taste', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('congestion', models.BooleanField(default=False)),
            ],
        ),
    ]
